name: release

on:
  release:
    types: [published]

jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: "Generate release changelog"
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: uplaod changelog
        uses: shogo82148/actions-upload-release-asset@v1.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: changelog

  docker:
    needs: changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      -
        name: Checkout
        uses: actions/checkout@v3
      - run: npm run build
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: user/app:latest
